# Auto-generated by programs/insert_reconvergence.py
# Contains custom `ssy label` instructions before conditional branches.

_start:
.Lpc_00000000:
    addi    x5, x31, 0
    slli    x6, x5, 0x6
    lui    x2, 0x2
    addi    x2, x2, 0
    sub    x2, x2, x6
    jal    x1, .Lpc_0000001c
.Lpc_00000018:
    jal    x0, .Lpc_00000018
main:
.Lpc_0000001c:
    addi    x15, x31, 0
    addi    x14, x0, 15
    ssy     .Lpc_00000078    # reconverge for branch at 0x24
    bltu    x14, x15, .Lpc_00000060
    lui    x13, 0x1
    slli    x14, x15, 0x2
    addi    x13, x13, 0
    add    x13, x13, x14
    addi    x12, x0, 111
    sw    x12, 0(x13)
    addi    x13, x0, 7
    ssy     .Lpc_00000078    # reconverge for branch at 0x44
    bltu    x13, x15, .Lpc_00000090
    lui    x15, 0x1
    addi    x15, x15, 256
    add    x15, x15, x14
    addi    x13, x0, 444
    sw    x13, 0(x15)
    jal    x0, .Lpc_00000078
.Lpc_00000060:
    slli    x14, x15, 0x2
    lui    x15, 0x1
    addi    x15, x15, 0
    add    x15, x15, x14
    addi    x13, x0, 222
    sw    x13, 0(x15)
.Lpc_00000078:
    lui    x15, 0x1
    addi    x15, x15, 128
    add    x15, x15, x14
    addi    x14, x0, 333
    sw    x14, 0(x15)
    jalr    x0, 0(x1)
.Lpc_00000090:
    lui    x15, 0x1
    addi    x15, x15, 256
    add    x15, x15, x14
    addi    x13, x0, 555
    sw    x13, 0(x15)
    jal    x0, .Lpc_00000078
