# Auto-generated by programs/insert_reconvergence.py
# Contains custom `ssy label` instructions before conditional branches.

_start:
.Lpc_00000000:
    addi    x5, x31, 0
    slli    x6, x5, 0x6
    lui    x2, 0x2
    addi    x2, x2, 0
    sub    x2, x2, x6
    jal    x1, .Lpc_0000001c
.Lpc_00000018:
    jal    x0, .Lpc_00000018
main:
.Lpc_0000001c:
    addi    x2, x2, -32
    sw    x8, 28(x2)
    sw    x9, 24(x2)
    sw    x18, 20(x2)
    sw    x19, 16(x2)
    sw    x20, 12(x2)
    addi    x12, x31, 0
    lui    x14, 0x1
    srli    x17, x12, 0x1
    lui    x10, 0x1
    addi    x15, x12, 1000
    andi    x17, x17, 1
    andi    x8, x12, 1
    addi    x13, x0, 0
    addi    x10, x10, 640
    addi    x28, x0, 23
    addi    x7, x14, 905
    addi    x18, x14, 1905
    addi    x5, x14, 904
    addi    x9, x14, 1904
    addi    x6, x0, 15
    andi    x30, x12, 4
    addi    x29, x14, -96
    addi    x11, x14, -1096
    addi    x19, x12, 1
    addi    x16, x0, 3
.Lpc_00000084:
    srl    x14, x12, x13
    andi    x14, x14, 1
    ssy     .Lpc_000000b0    # reconverge for branch at 0x8c
    bne    x14, x0, .Lpc_00000174
    addi    x14, x13, 10
    add    x15, x14, x15
    ssy     .Lpc_000000b0    # reconverge for branch at 0x98
    bgeu    x6, x12, .Lpc_000001ac
    addi    x14, x13, 200
    add    x14, x14, x15
    add    x15, x14, x29
    ssy     .Lpc_000000b0    # reconverge for branch at 0xa8
    bne    x30, x0, .Lpc_000000b0
    add    x15, x14, x11
.Lpc_000000b0:
    slli    x14, x13, 0x5
    add    x14, x14, x12
    slli    x14, x14, 0x2
    add    x14, x10, x14
    sw    x15, 0(x14)
    addi    x13, x13, 1
    ssy     .Lpc_000000cc    # reconverge for branch at 0xc8
    bne    x13, x16, .Lpc_00000084
.Lpc_000000cc:
    lui    x16, 0x1
    addi    x10, x0, 0
    addi    x13, x0, 0
    addi    x16, x16, 128
    addi    x28, x0, 1
    andi    x30, x12, 8
    andi    x29, x12, 16
    addi    x6, x0, 4
.Lpc_000000ec:
    slli    x14, x13, 0x3
    sll    x11, x28, x13
    sub    x14, x14, x13
    and    x11, x11, x12
    add    x14, x14, x15
    add    x17, x10, x15
    ssy     .Lpc_00000114    # reconverge for branch at 0x104
    bne    x11, x0, .Lpc_00000164
    addi    x15, x14, 63
    ssy     .Lpc_00000114    # reconverge for branch at 0x10c
    bne    x29, x0, .Lpc_00000114
    addi    x15, x14, 31
.Lpc_00000114:
    slli    x14, x13, 0x5
    add    x14, x14, x12
    slli    x14, x14, 0x2
    add    x14, x16, x14
    sw    x15, 0(x14)
    addi    x13, x13, 1
    addi    x10, x10, 11
    ssy     .Lpc_00000134    # reconverge for branch at 0x130
    bne    x13, x6, .Lpc_000000ec
.Lpc_00000134:
    lui    x14, 0x1
    lw    x8, 28(x2)
    slli    x12, x12, 0x2
    addi    x14, x14, 0
    add    x12, x14, x12
    sw    x15, 0(x12)
    lw    x9, 24(x2)
    lw    x18, 20(x2)
    lw    x19, 16(x2)
    lw    x20, 12(x2)
    addi    x2, x2, 32
    jalr    x0, 0(x1)
.Lpc_00000164:
    addi    x15, x17, 255
    ssy     .Lpc_00000114    # reconverge for branch at 0x168
    bne    x30, x0, .Lpc_00000114
    addi    x15, x17, 127
    jal    x0, .Lpc_00000114
.Lpc_00000174:
    addi    x14, x13, 20
    add    x14, x14, x15
    addi    x15, x13, 600
    add    x15, x15, x14
    ssy     .Lpc_000000b0    # reconverge for branch at 0x184
    bgeu    x28, x12, .Lpc_000000b0
    addi    x15, x13, 500
    add    x14, x15, x14
    add    x20, x14, x5
    ssy     .Lpc_0000019c    # reconverge for branch at 0x194
    bne    x8, x0, .Lpc_0000019c
    add    x20, x14, x9
.Lpc_0000019c:
    add    x15, x20, x7
    ssy     .Lpc_000000b0    # reconverge for branch at 0x1a0
    bne    x17, x0, .Lpc_000000b0
    add    x15, x20, x18
    jal    x0, .Lpc_000000b0
.Lpc_000001ac:
    addi    x14, x13, 100
    add    x20, x13, x12
    add    x15, x14, x15
    andi    x14, x20, 2
    addi    x20, x15, 1000
    ssy     .Lpc_000001c8    # reconverge for branch at 0x1c0
    beq    x14, x0, .Lpc_000001c8
    addi    x20, x15, 2000
.Lpc_000001c8:
    add    x14, x19, x13
    andi    x14, x14, 2
    addi    x15, x20, 1001
    ssy     .Lpc_000000b0    # reconverge for branch at 0x1d4
    beq    x14, x0, .Lpc_000000b0
    addi    x15, x20, 2001
    jal    x0, .Lpc_000000b0
