import argparse
import csv
from pathlib import Path

try:
    import matplotlib
    matplotlib.use("Agg")  # Use a file-only backend so this also works over SSH/Docker.
    import matplotlib.animation as animation
    import matplotlib.pyplot as plt
except ImportError as exc:
    raise SystemExit(
        "visualize.py needs matplotlib and pillow. Install them, or run: "
        "uv run --with matplotlib --with pillow python visualize.py"
    ) from exc

INPUT_CSV = Path("simulation_data.csv")
OUTPUT_GIF = Path("nbody_animation.gif")
FPS = 60
TRAIL_LENGTH = 60
PADDING = 15
BODY_COLORS = [
    "#FFD700", "#1E90FF", "#FF4500", "#32CD32",
    "#DA70D6", "#00CED1", "#FF69B4", "#ADFF2F",
]


def load_rows(path):
    # Read the CSV generated by ./nbody_x86 > simulation_data.csv.
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def detect_body_indices(row):
    # Detect every xN/yN pair instead of assuming a fixed body count.
    return sorted(
        int(name[1:])
        for name in row
        if name.startswith("x") and name[1:].isdigit() and f"y{name[1:]}" in row
    )


def collect_bodies(rows):
    # Convert CSV rows into one x/y history per body.
    body_indices = detect_body_indices(rows[0])
    bodies = []
    for idx in body_indices:
        xs = [int(row[f"x{idx}"]) for row in rows]
        ys = [int(row[f"y{idx}"]) for row in rows]
        bodies.append({"idx": idx, "xs": xs, "ys": ys})
    return bodies


def calculate_bounds(bodies):
    # Use all bodies and all frames to keep the camera fixed during the GIF.
    xs = [x for body in bodies for x in body["xs"]]
    ys = [y for body in bodies for y in body["ys"]]
    min_x, max_x = min(xs) - PADDING, max(xs) + PADDING
    min_y, max_y = min(ys) - PADDING, max(ys) + PADDING

    if min_x == max_x:
        max_x = min_x + 1
    if min_y == max_y:
        max_y = min_y + 1

    return min_x, max_x, min_y, max_y


def make_animation(rows, bodies, output_path, fps, trail_length):
    # Create a dark matplotlib figure for the animated body positions.
    fig, ax = plt.subplots(figsize=(8, 8))
    fig.patch.set_facecolor("#0b0f19")
    ax.set_facecolor("#0b0f19")
    ax.set_title("N-body GPU Program", color="white")
    ax.set_xlabel("X Position", color="white")
    ax.set_ylabel("Y Position", color="white")
    ax.tick_params(colors="white")
    ax.grid(True, linestyle="--", alpha=0.25)

    # Keep axes fixed so motion is easy to compare frame-to-frame.
    min_x, max_x, min_y, max_y = calculate_bounds(bodies)
    ax.set_xlim(min_x, max_x)
    ax.set_ylim(min_y, max_y)
    for spine in ax.spines.values():
        spine.set_color("white")

    # Build one point marker and one trail line for each body.
    scatters = []
    trails = []
    for body_num, body in enumerate(bodies):
        color = BODY_COLORS[body_num % len(BODY_COLORS)]
        size = 45
        edge_color = "black"
        zorder = 3
        if body["idx"] == 0:
            # Draw the central black hole as a dark fixed center with a bright rim.
            color = "#000000"
            edge_color = "#FFD700"
            size = 140
            zorder = 4
        scatter = ax.scatter([], [], c=color, s=size, edgecolors=edge_color, zorder=zorder)
        trail, = ax.plot([], [], c=color, alpha=0.55, linewidth=1.5, zorder=2)
        scatters.append(scatter)
        trails.append(trail)

    step_text = ax.text(
        0.02, 0.97, "", transform=ax.transAxes,
        color="white", fontsize=12, fontfamily="monospace", va="top",
    )

    def update(frame):
        # Draw current positions plus a short trailing path for each body.
        start = max(0, frame - trail_length)
        for body_num, body in enumerate(bodies):
            x = body["xs"][frame]
            y = body["ys"][frame]
            scatters[body_num].set_offsets([[x, y]])
            trails[body_num].set_data(body["xs"][start:frame + 1], body["ys"][start:frame + 1])
        step_text.set_text(f"step {rows[frame].get('step', frame)} / {len(rows) - 1}")
        return scatters + trails + [step_text]

    # Save the animation as a GIF using Pillow through matplotlib.
    anim = animation.FuncAnimation(fig, update, frames=len(rows), interval=1000 / fps, blit=True)
    writer = animation.PillowWriter(fps=fps)
    anim.save(output_path, writer=writer)
    plt.close(fig)


def parse_args():
    parser = argparse.ArgumentParser(description="Render nbody simulation_data.csv as a matplotlib GIF.")
    parser.add_argument("--input", type=Path, default=INPUT_CSV, help="CSV generated by ./nbody_x86")
    parser.add_argument("--output", type=Path, default=OUTPUT_GIF, help="GIF file to write")
    parser.add_argument("--fps", type=int, default=FPS, help="Frames per second for the output GIF")
    parser.add_argument("--trail", type=int, default=TRAIL_LENGTH, help="Number of previous steps to show as a trail")
    return parser.parse_args()


def main():
    args = parse_args()
    if not args.input.exists():
        raise SystemExit(f"{args.input} not found. Run ./nbody_x86 > {args.input} first.")

    rows = load_rows(args.input)
    if not rows:
        raise SystemExit(f"{args.input} is empty.")

    bodies = collect_bodies(rows)
    if not bodies:
        raise SystemExit(f"{args.input} has no xN/yN body columns.")

    make_animation(rows, bodies, args.output, args.fps, args.trail)
    print(f"Wrote {args.output} with {len(bodies)} bodies and {len(rows)} frames")


if __name__ == "__main__":
    main()
