import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Load the CSV data generated by the RISC-V/x86 C code
df = pd.read_csv('simulation_data.csv')

# Setup the figure and axis
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_title("N-Body Simulation Visualizer")
ax.set_xlabel("X Position")
ax.set_ylabel("Y Position")

# Calculate min and max bounds dynamically to fit all orbits
padding = 50
min_x = df[['x0', 'x1', 'x2']].min().min() - padding
max_x = df[['x0', 'x1', 'x2']].max().max() + padding
min_y = df[['y0', 'y1', 'y2']].min().min() - padding
max_y = df[['y0', 'y1', 'y2']].max().max() + padding

ax.set_xlim(min_x, max_x)
ax.set_ylim(min_y, max_y)

# Colors and relative sizes for the bodies (Sun, Planet 1, Planet 2)
colors = ['#FFD700', '#1E90FF', '#FF4500']
sizes = [500, 100, 100] 

scatters = []
lines = []

# Initialize the plot elements for each body
for i in range(3):
    # Scatter plot for the current position of the body
    scatter = ax.scatter([], [], c=colors[i], s=sizes[i], edgecolors='black', zorder=3)
    scatters.append(scatter)
    
    # Line plot for the orbital trail
    line, = ax.plot([], [], c=colors[i], alpha=0.5, zorder=2)
    lines.append(line)

# The function that updates the plot for each frame
def update(frame):
    trail_length = 60 # Number of past steps to show in the trail
    start_idx = max(0, frame - trail_length)
    
    for i in range(3):
        # Update body position
        current_x = df[f'x{i}'][frame]
        current_y = df[f'y{i}'][frame]
        scatters[i].set_offsets([[current_x, current_y]])
        
        # Update trail history
        trail_x = df[f'x{i}'][start_idx:frame+1]
        trail_y = df[f'y{i}'][start_idx:frame+1]
        lines[i].set_data(trail_x, trail_y)
        
    return scatters + lines

# Create the animation (interval is in milliseconds per frame)
ani = animation.FuncAnimation(fig, update, frames=len(df), interval=20, blit=True)

# Format the grid and background
plt.grid(True, linestyle='--', alpha=0.6)
ax.set_facecolor('#0b0f19') # Dark background for a space theme
fig.patch.set_facecolor('#0b0f19')
ax.tick_params(colors='white')
ax.xaxis.label.set_color('white')
ax.yaxis.label.set_color('white')
ax.title.set_color('white')
for spine in ax.spines.values():
    spine.set_color('white')

# Launch the visualizer
plt.show()