# Auto-generated by programs/insert_reconvergence.py
# Contains custom `ssy label` instructions before conditional branches.

_start:
.Lpc_00000000:
    addi    x5, x31, 0
    slli    x6, x5, 0x6
    lui    x2, 0x2
    addi    x2, x2, 0
    sub    x2, x2, x6
    jal    x1, .Lpc_0000001c
.Lpc_00000018:
    jal    x0, .Lpc_00000018
main:
.Lpc_0000001c:
    addi    x14, x31, 0
    addi    x15, x0, 15
    ssy     .Lpc_00000040    # reconverge for branch at 0x24
    bltu    x15, x14, .Lpc_00000058
    lui    x15, 0x1
    slli    x14, x14, 0x2
    addi    x15, x15, 128
    add    x15, x15, x14
    addi    x13, x0, 111
    sw    x13, 0(x15)
.Lpc_00000040:
    lui    x15, 0x1
    addi    x15, x15, 0
    add    x15, x15, x14
    addi    x14, x0, 333
    sw    x14, 0(x15)
    jalr    x0, 0(x1)
.Lpc_00000058:
    lui    x15, 0x1
    slli    x14, x14, 0x2
    addi    x15, x15, 128
    add    x15, x15, x14
    addi    x13, x0, 222
    sw    x13, 0(x15)
    jal    x0, .Lpc_00000040
